apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gallery-api
  namespace: metube-gallery
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: api.gallery.metube.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gallery-api
                port:
                  number: 80
  tls:
    - hosts:
        - api.gallery.metube.dk
      secretName: gallery-api-tls
