apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gallery-api
  namespace: argocd
  annotations:
    # Track the image in Harbor
    argocd-image-updater.argoproj.io/image-list: gallery-api=harbor.metube.dk/metube/gallery-api
    # Always pick newest tag
    argocd-image-updater.argoproj.io/update-strategy: newest
    # Secret for pulling private images
    argocd-image-updater.argoproj.io/app.pull-secret: secret:metube-gallery/harbor-creds
spec:
  project: default
  source:
    repoURL: https://github.com/andreasfrisch/cluster-apps.git
    targetRevision: main
    path: gallery-api/   # folder with your deployment.yml, service.yml, ingress.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: metube-gallery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
