apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-application
  namespace: hello-world
spec:
  project: default
  source:
    repoURL: https://github.com/andreasfrisch/cluster-apps.git
    targetRevision: main
    path: hello-world
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
